### PR TITLE
Turkish strings.xml

### PR DESCRIPTION
**Pull request by TeaqariaWTF**
I finally finished it, but there may be some mistakes, I hope you will update it soon so that I can see my mistakes if any.

Fixes #

### Changes description

  -

### CODE REVIEW

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
Please check when you have some time and let us know if there is anything else to make it compatible to merge.

**Comment by TeaqariaWTF** [comment]
> @alexdwork2018 Please check when you have some time and let us know if there is anything else to make it compatible to merge. I think the folder structure needs to be different (now is editing English).

There is no error that caught my eye when I checked

**Comment by The-Hidden-Hand** [comment]
I think there are two missing points for the translations to work. One is the language selector and also this new strings file have to be created inside a new folder only for the Turkish language. My experience with Android coding is limited so we have to wait for @alexdwork2018 to be available in the coming days so he can tell us.

**Comment by TeaqariaWTF** [comment]
> 

I guess there is nothing I can do at this stage

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand Yes, I will add the missing changes and include the translation in the next release. I will do it soon there are a couple of tasks left in the queue before this.

**Pull request merged**
